### ISSUE TITLE
Reconnect

### ISSUE THREAD

**Issue by JustBlackBird** [andrewrk/mpd.js#17]
The can be cases when connection to MPD server is lost. I think it will be useful to have a `reconnect` method inside of MPD client. In this case client code can just restore the connection without creating a new instance of MPD client.

I could provide a PR with such feature if the maintainer is interested in it.

**Comment by morbidick** [comment]
+1

**Comment by JustBlackBird** [comment]
More that year passed since I opened the issue. Now I see that reconnection should not be done inside of MPD client. Such features should be implemented at higher level, for example in a kind of pool.

If someone interested, there is a [Generic Pool](https://github.com/coopernurse/node-pool) for node.js which could be easily turned into MPD pool with reconnection and all other fancy stuff.

**Comment by ozanmuyes** [comment]
@JustBlackBird thanks for the solution advice, but how did you manage the generic pool to reconnect? I have followed the steps 1 and 2 on the generic-pool's README file, but right after first attempt my application terminates.

**Comment by JustBlackBird** [comment]
@ozanmuyes here is [an example](https://github.com/JustBlackBird/bluethroat/blob/master/lib/mpd_pool.js) of how I use Generic Pool with MPD client.

**Comment by ozanmuyes** [comment]
@JustBlackBird thank you.
