### ISSUE TITLE
Is MPD password supported?

### ISSUE THREAD

**Issue by neilscudder** [andrewrk/mpd.js#19]
I have tried a couple things to no avail

**Comment by andrewrk** [comment]
Yes it's groovebasin user name + "/" + groovebasin password. Apologies for the lack of documentation.

**Comment by andrewrk** [comment]
You might need to use the groovebasin web interface to set up users and passwords

**Comment by neilscudder** [comment]
Actually I meant the mpd password, as optionally specified in the mpd.conf

**Comment by andrewrk** [comment]
I understood. The password is not specified in a config file; it is configured using the groovebasin web interface. The mpd password is groovebasin username +"/" + groovebasin password

**Comment by neilscudder** [comment]
I am still not understanding you. I am using mpd not groovebasin. There is no username. My mpd.conf file has a password directive, as specified in the man page for mpd.conf:

password password@permissions
              This specifies a password for access to mpd.  The format is "password@permis‐
              sions" where permissions is a comma delimited list composed of "read", "add",
              "control", and/or "admin".  "read" allows for reading of the  database,  dis‐
              playing  the  current  playlist, and current status of mpd.  "add" allows for
              adding songs and loading playlists.  "control" allows for  all  other  player
              and  playlist manipulations.  "admin" allows the db to be updated and for the
              client to kill mpd.  An example value is  "somePassword@read,add".   Multiple
              password parameters may be specified.

Normally I use the mpc client, and invoke this with `mpc -h PASSWORD@HOST`

Thank you for your time.

**Comment by andrewrk** [comment]
I'm sorry, I was checking this on my phone and I mistakenly thought this was [another project](https://github.com/andrewrk/groovebasin).

As for the issue, have you tried `client.sendCommand("password@permissions")` ?

**Comment by neilscudder** [comment]
I have not tried it. I'm not currently using this so will close the issue for now. Thanks again

**Comment by terenc3** [comment]
Just in case someone is searching this.

`client.sendCommand(cmd("password", ["myPassword"]));`
